name: TinyTapeout datasheet
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          submodules: recursive
      - uses: TinyTapeout/tt-gds-action/docs@ihp-cmos5l
